language: cpp
dist: trusty

branches:
  only:
  - master
  - develop

#
# Build Dependencies
#
before_script:

  #
  # Update / Install CMake
  #
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      mkdir -p external/cmake
      pushd external/cmake
      wget https://cmake.org/files/v3.8/cmake-3.8.0-Linux-x86_64.sh
      chmod +x cmake-*-Linux-x86_64.sh
      ./cmake-*-Linux-x86_64.sh --exclude-subdir --skip-license
      export PATH="${PWD}/bin:$PATH"
      popd
    else
      if ! brew ls --version cmake &>/dev/null; then brew update; brew install cmake; fi
    fi

#
# Build Matrix
#
matrix:
  include:

  #
  # G++ 5
  #
  - os: linux
    env:
      - TEST="G++ 5"
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-5
          - g++-5
    script:
      - cmake -DCMAKE_CXX_COMPILER="g++-5" .
      - make
      - make tests
      - ctest

  #
  # G++ 6
  #
  - os: linux
    env:
      - TEST="G++ 6"
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-6
          - g++-6
    install:
      - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
      - tar xf lcov_1.11.orig.tar.gz
      - sudo make -C lcov-1.11/ install
      - gem install coveralls-lcov
    script:
      - cmake -DCMAKE_CXX_COMPILER="g++-6" -DCOVERAGE=1 .
      - make
      - make tests
      - ctest
    after_success:
      - lcov --directory . --capture --output-file coverage.info
      - lcov --remove coverage.info 'external/*' 'test/*' '/usr/*' --output-file coverage.info
      - lcov --list coverage.info
      - coveralls-lcov --repo-token ${COVERALLS_REPO_TOKEN} coverage.info

  #
  # Clang 3.8
  #
  - os: linux
    env:
      - TEST="Clang 3.8"
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-4.0
        packages:
          - clang-3.8
          - gcc-6
          - g++-6
    script:
      - cmake -DCMAKE_C_COMPILER=clang-3.8 -DCMAKE_CXX_COMPILER=clang++-3.8 .
      - make
      - make tests
      - ctest

  #
  # Clang 3.9
  #
  - os: linux
    env:
      - TEST="Clang 3.9"
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-3.9
        packages:
          - clang-3.9
          - gcc-6
          - g++-6
    script:
      - cmake -DCMAKE_C_COMPILER=clang-3.9 -DCMAKE_CXX_COMPILER=clang++-3.9 .
      - make
      - make tests
      - ctest

  #
  # Clang 4.0
  #
  - os: linux
    env:
      - TEST="Clang 4.0"
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-4.0
        packages:
          - clang-4.0
          - gcc-6
          - g++-6
    script:
      - cmake -DCMAKE_C_COMPILER=clang-4.0 -DCMAKE_CXX_COMPILER=clang++-4.0 .
      - make
      - make tests
      - ctest

  #
  # XCode 8.3
  #
  - os: osx
    env:
      - TEST="XCode 8.3"
    osx_image: xcode8.3
    script:
      - cmake .
      - make
      - make tests
      - ctest

  #
  # XCode 9.2
  #
  - os: osx
    env:
      - TEST="XCode 9.2"
    osx_image: xcode9.2
    script:
      - cmake .
      - make
      - make tests
      - ctest
